# -*- coding: utf-8 -*-
# Generated by Django 2.2.20 on 2021-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0006_unique_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Published"
            ),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name. Can only be alphanumeric with hyphens as word delimiter.",
                max_length=128,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="sermonseries",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name. Can only be alphanumeric with hyphens as word delimiter.",
                max_length=128,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
