# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="name_en",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="attachment",
            name="name_ru",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="attachment",
            name="name_uk",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
    ]
