# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_translating_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
    ]
